# netlify.toml

[dev]
  command    = "npm run dev"
  port       = 8888
  targetPort = 3000
  framework  = "vite"
  functions  = "functions"

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "functions"

# 1) Fila de redirect para API—force asegura que NUNCA sirva index.html para /api/*
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true

# 2) Catch-all para SPA: sólo después de /api/*
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
