# netlify.toml

[dev]
  # Usa tu script de dev para arrancar Vite
  command   = "npm run dev"
  # Puerto donde Netlify expondrá tu sitio (puede ser 8888)
  port      = 8888
  # Puerto donde corre realmente Vite (tú lo pusiste en vite.config.js)
  targetPort = 3000
  # Indica que esto es un proyecto Vite
  framework = "vite"
  functions = "functions"

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "functions"

[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
