# netlify.toml

[dev]
  # Comando para levantar Vite en modo dev
  command    = "npm run dev"
  # Puerto público que expondrá Netlify Dev
  port       = 8888
  # Puerto interno donde corre Vite (coincide con vite.config.js)
  targetPort = 3001
  framework  = "vite"
  functions  = "functions"

[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "functions"

# Redirige /api/* a tus serverless functions
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200
  force  = true

# Catch-all para tu SPA
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
